backend/models/Perizinan.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "perizinan".
 *
 * @property int $id_perizinan
 * @property string $no_izin
 * @property string $nama_pemilik
 * @property string $lokasi
 * @property string $file
 */
class Perizinan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'perizinan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['no_izin', 'nama_pemilik', 'lokasi', 'file'], 'required'],
            [['no_izin', 'nama_pemilik', 'file'], 'string', 'max' => 455],
            [['lokasi'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_perizinan' => 'Id Perizinan',
            'no_izin' => 'No Izin',
            'nama_pemilik' => 'Nama Pemilik',
            'lokasi' => 'Lokasi',
            'file' => 'File',
        ];
    }
}

frontend/models/Perizinan.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "perizinan".
 *
 * @property int $id_perizinan
 * @property string $no_izin
 * @property string $nama_pemilik
 * @property string $lokasi
 * @property string $file
 */
class Perizinan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'perizinan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['no_izin', 'nama_pemilik', 'lokasi', 'file'], 'required'],
            [['no_izin', 'nama_pemilik'], 'string', 'max' => 455],
            [['file'], 'file','skipOnEmpty'=>TRUE,'extensions'=>'pdf'],
            [['lokasi'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_perizinan' => 'Id Perizinan',
            'no_izin' => 'No Izin',
            'nama_pemilik' => 'Nama Pemilik',
            'lokasi' => 'Lokasi',
            'file' => 'File',
        ];
    }
}

backend/controllers/PerizinanController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Perizinan;
use backend\models\PerizinanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PerizinanController implements the CRUD actions for Perizinan model.
 */
class PerizinanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Perizinan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PerizinanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Perizinan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Perizinan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Perizinan();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_perizinan]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Perizinan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_perizinan]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Perizinan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Perizinan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Perizinan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Perizinan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/PerizinanController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Perizinan;
use frontend\models\PerizinanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use app\models\UploadForm;

/**
 * PerizinanController implements the CRUD actions for Perizinan model.
 */
class PerizinanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Perizinan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PerizinanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Perizinan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Perizinan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Perizinan();
        if ($model->load(Yii::$app->request->post())){
          $model->file = "Initial";
          $model->save();
          $id_perizinan = $model->id_perizinan;
          $file = UploadedFile::getInstance($model, 'file');
          $fileName = $file->baseName . '.' . $file->getExtension();
          $file->saveAs(Yii::getAlias('@frontend') . '/web/File Perizinan/' . $fileName);
          $model->file = $fileName;
          $model->save();

          return $this->redirect(['index', 'id' => $model->id_perizinan]);
      }else{
        return $this->render('create', [
            'model' => $model,
        ]);
    }
}

 //Action Download
 public function actionDownload($id) 
 { 
     $download = Perizinan::findOne($id); 
     $path=Yii::getAlias('@frontend') . '/web/File Perizinan/' . $download->file;
 
     if (file_exists($path)) {
         return Yii::$app->response->sendFile($path);
     }
 }

    /**
     * Updates an existing Perizinan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_perizinan]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Perizinan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Perizinan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Perizinan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Perizinan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    public function actionViewFile($fileName){
        $file = Yii::getAlias('@frontend' . '/web/File Perizinan/' . $fileName);
        return Yii::$app->response->sendFile($file, NULL, ['inline' => TRUE]);
    }
}

frontend/views/perizinan/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Perizinan */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="perizinan-form">

	<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

	<div class="row">
		<div class="col-md-8 col-sm-8">
			<?= $form->field($model, 'nama_pemilik')->textInput(['maxlength' => true]) ?>
		</div>
	</div>

	<?= $form->field($model, 'file')->fileInput() ?>

	<div class="form-group">
    <?= Html::submitButton($model->isNewRecord ? 'Simpan' : 'Selesai', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>

    <?= Html::a('Batal', ['index'], ['class' => 'btn btn-danger']) ?>
</div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/perizinan/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PerizinanSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="perizinan-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_perizinan') ?>

    <?= $form->field($model, 'no_izin') ?>

    <?= $form->field($model, 'nama_pemilik') ?>

    <?= $form->field($model, 'lokasi') ?>

    <?= $form->field($model, 'file') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/perizinan/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Perizinan */

$this->title = 'Create Perizinan';
$this->params['breadcrumbs'][] = ['label' => 'Perizinans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="perizinan-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/perizinan/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PerizinanSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Perizinan';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="perizinan-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Perizinan', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

    
            'no_izin',
            'nama_pemilik',
            'lokasi',
            'file',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

frontend/views/perizinan/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Perizinan */

$this->title = 'Update Perizinan: ' . $model->id_perizinan;
$this->params['breadcrumbs'][] = ['label' => 'Perizinans', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_perizinan, 'url' => ['view', 'id' => $model->id_perizinan]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="perizinan-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/perizinan/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Perizinan */

$this->title = 'Data Perizinan';
$this->params['breadcrumbs'][] = ['label' => ' Perizinan', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="perizinan-view">

	<h1><?= Html::encode($this->title) ?></h1>


	<?= DetailView::widget([
		'model' => $model,
		'attributes' => [
			'nama_pemilik',
			['attribute' => 'file',
			'label' => 'File Pemilik',
			'format' => 'html',
			'value' => 
			function($model){
				return Html::a($model->file, ['perizinan/download', 'id'=> $model->id_perizinan]);
			}
		],
		
	],
]) ?>

</div>